WARNING: No test specified, defaulting to first test defined (_)
TRACE: Initialized test input buffer with data from `/home/akhila/fuzzer_packages/fuzzedpackages/diffusr/inst/testfiles/neighbors_/neighbors__output/b2a680a491c62b8e3c18e1b6a93cfd7bf1182ccb.crash`
TRACE: Running: _ from /home/akhila/fuzzer_packages/fuzzedpackages/diffusr/inst/testfiles/neighbors_/neighbors__DeepState_TestHarness.cpp(13)
input starts
EXTERNAL: qs v0.23.5.

node_idxs values: 1926209628 1434416441 88940557 1485040860 -1728786011 977540242 -1593973169 -66270866 -613823696 -398431762 -1920271387 233292454 -611103979 -681597065 1552795224 -1718565004 -107830046
W values: 1.75933e-114 6.79398e+55 3.80927e-156 2.62539e+129 1.98743e+154
8.24222e-287 7.20263e+40 1.33550e+204 6.85769e-16 1.51886e-282

k values: 1368557731
input ends
==2446362==  If you believe this happened as a result of a stack
==2446362==  overflow in your program's main thread (unlikely but
==2446362==  possible), you can try to increase the size of the
==2446362==  main thread stack using the --main-stacksize= flag.
==2446362==  The main thread stack size used in this run was 8388608.
ERROR: Crashed: _
ERROR: Test case /home/akhila/fuzzer_packages/fuzzedpackages/diffusr/inst/testfiles/neighbors_/neighbors__output/b2a680a491c62b8e3c18e1b6a93cfd7bf1182ccb.crash crashed
